---
- name: List packages and report
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
  - name: Generate RPM list
    yum:
      list: installed
    register: pkg_list

  - name: Report RPM list
    debug:
      msg: "{{item.name}}"
    with_items: "{{pkg_list.results}}"