---
- name: List packages and report
  hosts: all
  gather_facts: false
  become: false

  tasks:
  - name: Generate RPM list
    yum:
      list: installed
    register: pkg_list

  - name: Report RPM list
    debug:
      var:  item.name
    with_items: "{{pkg_list.results}}"